#!/bin/bash

if [[ "$((RANDOM%2))" -eq 1 ]]; then
    awk '$0!=f {print f; f=$0}'
    echo "AWK"
else
    while read; do
        if [[ "$LAST" != "$REPLY" ]]; then
            LAST="$REPLY"
            echo "$REPLY"
        fi
    done
    echo "BASH"
fi

    
