#!/usr/bin/env bash

set -euo pipefail
[[ "${TRACE:-}" ]] && set -x


connect() {
        
        xrandr --output HDMI-1 --right-of LVDS-1 --auto
        xrandr --output VGA-1 --right-of LVDS-1 --auto
        logger -t "display" "connected"
}

disconnect() {

	xrandr --output HDMI-1 --off
	xrandr --output VGA-1 --off
        logger -t "display" "disconnected"
}

main() {
    
    if xrandr | grep -qE "(VGA|HDMI)-1 connected"; then
        connect
    else
        disconnect
    fi
    
    # Update background for all monitors
    feh --bg-center /home/rat/Pictures/background_new.png
}

main
