#!/bin/bash

### Этот скрипт нужен мне для автоматического подключения монитора, срабатывает на триггере в udev

#export DISPLAY=:0
#export XAUTHORITY=/home/rat/.Xauthority

RESOLUTION="1366 768"

function connect(){
        $(cvt $RESOLUTION | awk '/Modeline/{for (i=2;i<=NF;i++) printf $i" " } END{print ""}' | sed 's/_[^"]*//;s/^/xrandr --newmode /')
        # Эта команда выдает строку для создания нового мода для xrandr и сразу же запускат, ниже пример для разрешения 1366x768
        # xrandr --newmode "1368x768"   85.25  1368 1440 1576 1784  768 771 781 798 -hsync +vsync
        
        xrandr --addmode VGA-1 1368x768
        xrandr --output VGA-1 --right-of LVDS-1 --mode $(xrandr | awk '/VGA-1 connected/{flag=1;next}/HDMI/{flag=0}flag' | sort -nr | awk 'NR==1{print $1}')
}

function disconnect(){
	xrandr --output VGA-1 --off
}

# init
xrandr | grep -q "VGA-1 connected" && connect || disconnect

# Update background for all monitors
feh --bg-center /home/rat/Pictures/background.jpeg
