#!/usr/bin/env bash

# I bound this script to my PrintScreen
# This script make a screenshot, and put it into your clipboard

scrot -u /tmp/foo.png
xclip -selection clipboard -t image/png -i /tmp/foo.png
rm /tmp/foo.png
