#!/usr/bin/env bash

# This script make a screenshot, and put it into your clipboard
# I bound it to my PrintScreen button

# Usage:
# prtscr - Print screen current window to clipboard
# prtscr -s - Print screen selection to clipboard

set -eu
[[ "${TRACE:-}" ]] && set -x


cleanup() {

    rm -rf "${tmp_file}"
}

main() {

    readonly tmp_file="$(mktemp -t scrot.XXXXXXXXX.png)"
    local flags=("$@")
    : "${flags:=-u}"
    
    scrot "${tmp_file}" -z "${flags[@]}" -e 'xclip -selection clipboard -t image/png -i $f'

}

trap cleanup EXIT
main "$@"
