#!/usr/bin/env bash

_save_last() {
    local last="$1"
    echo "last=${last}" > ".last"
}

_get_series() {
    local regexp='[sS][0-9]+[eE][0-9]+'
    for file in "${formats[@]}"; do
        [[ "${file}" =~ ${regexp} ]] && echo "${file}"
    done | sort -u
}

_main() {
    readonly formats=(*avi *mkv)
    readonly show_path="${1:=.}"
    local current
    
    command cd "${show_path}"
    
    if [[ -f ".last" ]]; then
        source ".last"
        current="$(_get_series | sed -n "/${last}/{n;p;}")"
    else
        current="$(_get_series | head -1)"
    fi
    
    mpv ./*"${current}"* &>/dev/null &
    _save_last "${current}"
    command cd - >/dev/null
}

_main "$@"
