#!/usr/bin/env bash
RESOLUTION="1920 1080"
$(cvt $RESOLUTION | awk '/Modeline/{for (i=2;i<=NF;i++) printf $i" " } END{print ""}' | sed 's/_[^"]*//;s/^/xrandr --newmode /;s/"//g')
xrandr --addmode VGA-1 1920x1080
xrandr --output VGA-1 --mode $(xrandr | awk '/VGA-1 connected/{flag=1;next}/VGA/{flag=0}flag' | sort -nr | awk 'NR==1{print $1}')
xrandr --output LVDS-1 --off
feh --bg-center /home/rat/Pictures/background_new.png
