#!/usr/bin/env bash

set -euo pipefail
[[ "${TRACE:-}" ]] && set -x

main() {
    # $1 - ip for getting info, if not defined, used from ifconfig.io
    local ip=("${@:-$(curl -s ifconfig.io)}")

    for i in "${ip[@]}"; do
        curl -s "ipinfo.io/${i}" 
    done | jq -s '.'
}

main "$@"
