#!/usr/bin/env bash
# ~/.bash_prompt

function timer_now {
    date +%s%N
}

function timer_start {
    timer_start=${timer_start:-$(timer_now)}
}

function timer_stop {
    local delta_us=$((($(timer_now) - $timer_start) / 1000))
    local us=$((delta_us % 1000))
    local ms=$(((delta_us / 1000) % 1000))
    local s=$(((delta_us / 1000000) % 60))
    local m=$(((delta_us / 60000000) % 60))
    local h=$((delta_us / 3600000000))
    # Goal: always show around 3 digits of accuracy
    if ((h > 0)); then timer_show=${h}h${m}m
    elif ((m > 0)); then timer_show=${m}m${s}s
    elif ((s >= 10)); then timer_show=${s}.$((ms / 100))s
    elif ((s > 0)); then timer_show=${s}.$(printf %03d $ms)s
    elif ((ms >= 100)); then timer_show=${ms}ms
    elif ((ms > 0)); then timer_show=${ms}.$((us / 100))ms
    else timer_show=${us}us
    fi
    unset timer_start
}


set_prompt () {

    Last_Command=$? # Must come first!

    timer_stop

    Blue='\[\e[01;34m\]'
    White='\[\e[01;37m\]'
    Red='\[\e[00;31m\]'
    Light_Red='\[\e[01;31m\]'
    Green='\[\e[01;32m\]'
    Reset='\[\e[00m\]'

    if [[ $Last_Command == 0 ]]; then
        PS1="$Green"
    else
        PS1="$Red"
    fi
    
    PS1+="[\$?]" # Exit code of last command

    PS1+="$Light_Red[$timer_show]" # Last command execution time

    PS1+="$Red[$USER]" # Current user
    PS1+="$Green\$(git_branch)" # Git branch (if you are in a git directory)
    PS1+="$Light_Red\\w: $Reset" # ':'
}

trap 'timer_start' DEBUG
PROMPT_COMMAND='set_prompt'
