#!/bin/bash
#~/.bash_functions

. ~/.bash_cd

function ssk { ssh kioller_a@$1; }

function cdg {
    TEMP_PWD=$PWD
    while [ ! -d .git ]
    do
            cd ..
    done
    OLDPWD=$TEMP_PWD
}

function gcp {
    # [g]it [c]ommit [p]ush
    cdg
    git add . && git commit -m "${1:-"Fast commit by Cuttlerat"}" && git push 
    cd -
}

