#!/bin/bash
#~/.bash_aliases

alias ssh='TERM=xterm ssh'
alias vim='nvim'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias :q='exit'
alias dc='cd'
alias sl='ls'
alias ambient='mpv http://prem2.di.fm:80/ambient_hi?ba648c26fe153861ecba7e26'
