#!/usr/bin/env bash
# ~/.bash_aliases

# Docker
alias dupb='sudo docker-compose up --build'
alias dlog='sudo docker-compose logs -f'
alias ddown='sudo docker-compose down'
alias dexec='sudo docker-compose exec'
alias dup='sudo docker-compose up'
# Pacman
alias update='sudo pacman -Syu'
alias remove='sudo pacman -Rs'
alias install='sudo pacman -S'
# Editors
alias vi='vim'
# Misspellings
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias :q='exit'
alias dc='cd'
alias sl='ls'
# Translation
alias ru='trans -s en -t ru'
alias en='trans -s ru -t en'
# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
# Other
alias ambient="mpv 'http://hot.friezy.ru/?radio=di&station=ambient&bitrate=320'"
alias cdg='cd $(dirname $(git rev-parse --git-dir 2>&- || echo .))'
alias ssh='TERM=xterm ssh'
alias vdc='vim docker-compose.yml'
alias vpn='sudo pon EPAM debug dump logfd 2 nodetach'
alias rdp="xfreerdp /sound:sys:pulse /microphone:sys:pulse +fonts \"/u:${RDP_USERNAME}\" \"/v:${RDP_HOSTNAME}\" /size:955x1185 /compression"
