#!/bin/bash

# It was a bad idea, I was going to write a script which makes a regexp for IP address with CIDR, but while I was writing it, I found this https://rgxg.github.io/
# So I think it's finished and I'm gonna to delete this

for IP in $@
{
    CIDR=${IP/#*\//}
    IP=${IP/%\/*/}
    SUFIX=$[((CIDR-1)/8)+1]
    IP=$(awk -F'.' "{for (i=1;i<=$SUFIX;i++) printf \$i\".\"}{for (j=4;j>$SUFIX;j--) printf \"\\\d+.\"}END{print \"\"}"<<<$IP | sed 's/\.$//')
    case $[CIDR%8] in
        0)
            ;;
        1)

            ;;
        2)
            ;;
        3)
            ;;
        4)
            ;;
        5)
            ;;
        6)
            ;;
        7)
            ;;
    esac

    echo $IP $CIDR

    #IP=${IP//./\\.}
}

